/*
 * generated by Xtext 2.15.0
 */
package org.xtext.spring.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.spring.springConfigJava.ui.internal.SpringConfigJavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpringConfigDslJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpringConfigJavaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpringConfigJavaActivator activator = SpringConfigJavaActivator.getInstance();
		return activator != null ? activator.getInjector(SpringConfigJavaActivator.ORG_XTEXT_SPRING_SPRINGCONFIGDSLJAVA) : null;
	}

}
