/*
 * generated by Xtext 2.15.0
 */
package org.xtext.spring.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.spring.springConfigJava.ui.internal.SpringConfigJavaActivator;

public class SpringConfigDslJavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpringConfigJavaActivator.getInstance().getInjector("org.xtext.spring.SpringConfigDslJava");
	}

}
