/**
 * generated by Xtext 2.15.0
 */
package org.xtext.spring.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.spring.ui.AbstractSpringConfigDslJavaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SpringConfigDslJavaUiModule extends AbstractSpringConfigDslJavaUiModule {
  public SpringConfigDslJavaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
