/**
 * generated by Xtext 2.15.0
 */
package org.xtext.spring.ide;

import org.xtext.spring.ide.AbstractSpringConfigDslJavaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SpringConfigDslJavaIdeModule extends AbstractSpringConfigDslJavaIdeModule {
}
