/**
 * generated by Xtext 2.15.0
 */
package org.xtext.spring.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.spring.SpringConfigDslJavaRuntimeModule;
import org.xtext.spring.SpringConfigDslJavaStandaloneSetup;
import org.xtext.spring.ide.SpringConfigDslJavaIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SpringConfigDslJavaIdeSetup extends SpringConfigDslJavaStandaloneSetup {
  @Override
  public Injector createInjector() {
    SpringConfigDslJavaRuntimeModule _springConfigDslJavaRuntimeModule = new SpringConfigDslJavaRuntimeModule();
    SpringConfigDslJavaIdeModule _springConfigDslJavaIdeModule = new SpringConfigDslJavaIdeModule();
    return Guice.createInjector(Modules2.mixin(_springConfigDslJavaRuntimeModule, _springConfigDslJavaIdeModule));
  }
}
